runtime: php83

entrypoint: serve api/index.php

automatic_scaling:
  max_instances: 20

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

# Serve php scripts.
- url: /(.+\.php)$
  script: auto

# Default handler
- url: /.*
  script: auto